version: '3.7'
volumes:
  pgdata:

services:
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - rabbitmq
      - celery_workers
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: fampay
      POSTGRES_USER: fampay
      POSTGRES_PASSWORD: fampay
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:3.7-alpine
  celery_workers:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    command: celery -A youtube_search worker --loglevel=info
    depends_on:
      - rabbitmq
      - postgres
