version: '3.7'
volumes:
  pgdata:

services:
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - 8000:8000
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: fampay
      POSTGRES_USER: fampay
      POSTGRES_PASSWORD: fampay
    ports:
      - 5432:5432
