# Generated by Django 3.0.5 on 2020-04-30 06:57

import datetime
from django.db import migrations, models
import youtube_search.helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDetails',
            fields=[
                ('id', models.CharField(default=youtube_search.helper.get_24_char_uuid, max_length=24, primary_key=True, serialize=False)),
                ('thumbnail_url', models.URLField(max_length=2000)),
                ('title', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=500)),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('platform', models.CharField(max_length=20)),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 4, 30, 6, 57, 27, 852677))),
            ],
            options={
                'verbose_name': 'Video Details',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='YoutubeTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('page_token', models.CharField(max_length=10, unique=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 4, 30, 6, 57, 27, 853326))),
            ],
            options={
                'verbose_name': 'Youtube page tokens',
                'ordering': ['-created'],
            },
        ),
    ]
